openapi: 3.0.0

info:

  title: TheCatAPI

  description: A simple API to fetch cat images, breeds, and other cat-related data.

  version: 1.0.0

servers:

  - url: https://api.thecatapi.com/v1

    description: TheCatAPI server

tags:

  - name: Cats

    description: Operations related to cats

paths:

  /images/search:

    get:

      tags:

        - Cats

      summary: Get random cat images

      description: Retrieve random cat images based on optional filters.

      parameters:

        - name: limit

          in: query

          description: Number of results to return (default is 1, max is 10)

          schema:

            type: integer

            default: 1

        - name: size

          in: query

          description: Size of the image (full, med, small, thumb)

          schema:

            type: string

            enum: [full, med, small, thumb]

            default: full

        - name: mime_types

          in: query

          description: Filter by image type (jpg, png, gif)

          schema:

            type: string

            enum: [jpg, png, gif]

        - name: breed_id

          in: query

          description: Filter by breed ID

          schema:

            type: string

      responses:

        '200':

          description: A JSON array of cat images

          content:

            application/json:

              schema:

                type: array

                items:

                  $ref: '#/components/schemas/CatImage'

        '400':

          description: Invalid parameters

        '401':

          description: Unauthorized (missing or invalid API key)
 
 